apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aira
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ktb-goorm-jaksim3/Aira_V3_GitOps.git'
    targetRevision: HEAD
    path: "."
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # 만약 Namespace가 미리 안만들어져 있을 경우
      - CreateNamespace=true