apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 730335258114.dkr.ecr.ap-northeast-2.amazonaws.com/aira/backend:latest
        ports:
        - containerPort: 8080
