apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 730335258114.dkr.ecr.ap-northeast-2.amazonaws.com/aira/backend:latest
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        env:
        # 비민감 설정: ConfigMap에서 주입
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: MYSQL_DATABASE
        - name: ALGORITHM
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ALGORITHM
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ACCESS_TOKEN_EXPIRE_MINUTES
        - name: GPT_WORKER_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GPT_WORKER_URL
        # 민감 정보: Secret에서 주입
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: application
  annotations:
    #Instance Mode로 대상 그룹에 등록. Pod 기반의 오토스케일링. HPA로 Pod 수가 변경될 때마다 대상 그룹이 자동으로 업데이트
    service.beta.kubernetes.io/aws-load-balancer-target-type: ip  
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
---
#Horizontal Pod Autoscaler. CPU, 메모리 등 메트릭 기반 스케일 인/아웃
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: application
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50