apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 730335258114.dkr.ecr.ap-northeast-2.amazonaws.com/aira/frontend:latest
        ports:
        - containerPort: 80
